### PR TITLE
fix(field): `optionFilterProp` doesn't work with LightFilter

### LINKED ISSUE #6564: 🐛[BUG] optionFilterProp doesn't work with LightFilter
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

`Select` component has a prop `optionFilterProp` to control the filtering behaviour and `ProFormSelect` component passes it to `Select` through `fieldProps`.
But if I use `ProFormSelect` with `LightFilter`, `optionFilterProp` doesn't work.

### 📷 复现步骤

https://codesandbox.io/s/qing-liang-shai-xuan-forked-8vmbeo?file=/App.tsx

### 🏞 期望结果

`optionFilterProp=label` can filter only by label, and `optionFilterProp=value` can filter only by value with `LightFilter`.

### 💻 复现代码

https://codesandbox.io/s/qing-liang-shai-xuan-forked-8vmbeo?file=/App.tsx

### PR DESCRIPTION
**Pull request by kungege**
Fixes #6564

### CODE REVIEW

File: packages/utils/src/components/FieldLabel/style.ts [hunk 1]
```diff
@@ -88,7 +88,7 @@ const genProStyle: GenerateStyle<ProToken> = (token) => {
         height: '32px',
         paddingBlock: 0,
         paddingInline: 12,
-        border: `${token.lineWidth} solid ${token.colorBorder}`,
+        border: `${token.lineWidth}px solid ${token.colorBorder}`,
```
Comment (kungege) [inline packages/utils/src/components/FieldLabel/style.ts:91]: ref #6576

**Comment by chenshuai2144** [comment]
要不要加个测试，顺便优化下代码感觉太长了

**Comment by kungege** [comment]
> 要不要加个测试，顺便优化下代码感觉太长了

done, PTAL.
